<a href="https://colab.research.google.com/github/devansh2991/Python-Training/blob/main/Day-6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class bankaccount:
  def __init__(self, balance):
    self.balance = balance
  def deposit(self, amount):
    self.balance += amount
    return self.balance
  def withdraw(self, amount):
    if self.balance >= amount:
      self.balance -= amount
      return self.balance
  def get_balance(self):
    return self.balance

acc = bankaccount(500)
print(acc.get_balance())
print(acc.deposit(500))
print(acc.withdraw(200))


import numpy as np

a = np.array([1,2,3,4])
b = np.zeros((2,3))
c = np.ones((2,3))
d = np.full((2,3), 7)
e = np.arange(0, 10, 2)
print(a,b,c,d,e)

a.shape[0]

reshaped = a.reshape(2,2)
print(reshaped)

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0:2, 1:3])

x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.sqrt(x))
print(np.sum(x, axis=0))

rand = np.random.rand(3,3)
rand_ints = np.random.randint(0,10,(2,3))
normal_dist = np.random.normal(1,2,5)
print(rand)
print(rand_ints)
print(normal_dist)


500
1000
800
[1 2 3 4] [[0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]] [[7 7 7]
 [7 7 7]] [0 2 4 6 8]
[[1 2]
 [3 4]]
[[20 30]
 [50 60]]
[1.         1.41421356 1.73205081]
6
[[0.4917372  0.06969897 0.01723251]
 [0.15672109 0.91988836 0.96001169]
 [0.25088064 0.28883002 0.87502722]]
[[9 3 2]
 [4 2 0]]
[ 3.30033729  0.71389378 -3.61825779 -0.66216954  2.72599395]
